//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal precioCosto { get; set; }
        public decimal utilidad { get; set; }
        public int impuesto { get; set; }
        public decimal precioVenta { get; set; }
        public string categoria { get; set; }
        public string proveedor { get; set; }
        public bool estado { get; set; }
    }
}
