//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal precioCosto { get; set; }
        public decimal utilidad { get; set; }
        public int idImpuesto { get; set; } 
        public decimal precioVenta { get; set; }
        public int idCategoria { get; set; }
        public string idProveedor { get; set; }
        public bool estado { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        public virtual tbImpuestos tbImpuestos { get; set; } 
        public virtual tbProveedores tbProveedores { get; set; }
    }
}
